import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {Footer,Navbar} from "@/components";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Metaverseus",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <link rel="preconnect" href="https://stijndv.com" />
      <link rel="stylesheet" href="https://stijndv.com/fonts/Eudoxus-Sans.css" />
    </head>
      <body className={`${inter.className} bg-gray-900 overflow-x-hidden`}>
        {children}
        
      </body>
    </html>
  );
}
